const SIGN_IN_START = 'SIGN_IN_START'
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
const SIGN_OUT = 'SIGN_OUT'

export { SIGN_IN_START, SIGN_IN_SUCCESS, SIGN_IN_ERROR, SIGN_OUT }
